[package]
name = "cipharius/msgpack-luau"
description = "A pure MessagePack binary serialization format implementation in Luau."
version = "0.1.1"
license = "MIT"
authors = ["Valts Liepiņš <cipharius@pm.me>"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"

[dependencies]
TestEZ = "roblox/testez@0.4.1" # NOTE Dev dependency

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"
